[package]
name = "wminspect"
version = "0.1.0"
authors = ["Sian Cao <yinshuiboy@gmail.com>"]
links = "xcb"
build = "build.rs"

[dependencies]
#x11 = "2.12.1"
xcb = "0.7.6"
getopts = "*"
colored = "1.4"
