[package]
name = "wminspect"
version = "0.1.0"
authors = ["Sian Cao <yinshuiboy@gmail.com>"]
links = "xcb"
build = "build.rs"

[dependencies]
#x11 = "2.12.1"
libc = "*"
xcb = {version = "0.7.6", features = ["thread"]}
getopts = "0.2.*"
colored = "1.4"
timer = "*"
crossbeam = "*"
regex = "*"
lazy_static = "*"
serde = "*"
