[package]
name = "wminspect"
version = "0.1.0"
authors = ["Sian Cao <yinshuiboy@gmail.com>"]
links = "xcb"
build = "build.rs"

[dependencies]
libc = "*"
xcb = {version = "0.8.*", features = ["thread"]}
colored = "1.4"
timer = "*"
crossbeam = "*"
regex = "*"
lazy_static = "*"
serde = "*"
clap = "2.27.*"
