name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb1-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-icccm4-dev
    
    - name: Build release
      run: cargo build --release --verbose
    
    - name: Create release binaries
      run: |
        mkdir -p release
        cp target/release/wminspect release/
        tar -czf release/wminspect-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz -C release wminspect
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/wminspect-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
        body_path: CHANGELOG.md
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
      
    - name: Build and push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t wminspect:${{ github.ref_name }} -t wminspect:latest .
        docker tag wminspect:${{ github.ref_name }} ${{ secrets.DOCKER_USERNAME }}/wminspect:${{ github.ref_name }}
        docker tag wminspect:latest ${{ secrets.DOCKER_USERNAME }}/wminspect:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/wminspect:${{ github.ref_name }}
        docker push ${{ secrets.DOCKER_USERNAME }}/wminspect:latest
